In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr) #[1 2 3 4 5] no commas
print("Type", type(arr))

Array: [1 2 3 4 5]
Type <class 'numpy.ndarray'>


In [2]:
# Addition of two arrays
import numpy as np
arr_1 = np.array([10, 20, 30, 40, 50])

arr_2 = np.array([1, 2, 3, 4, 5])

arr_3 = arr_1 + arr_2
print("Sum of two arrays:", arr_3) #[11 22 33 44 55]

Sum of two arrays: [11 22 33 44 55]


In [3]:
# Addition of two arrays

import numpy as np

arr_1 = np.array([10, 20, 30, 40, 50])

arr_2 = np.array([1, 2, 3, 4, 5])

arr_3 = arr_1 + arr_2
print("Sum of two arrays:", arr_3) #[11 22 33 44 55]

Sum of two arrays: [11 22 33 44 55]


In [4]:
import numpy as np

arr_1 = np.array([10, 20, 30, 40, 50])

arr_2 = np.array([1, 2, 3, 4, 5])

arr_3 = arr_1 - arr_2
print(arr_3)

[ 9 18 27 36 45]


In [5]:
import numpy as np

arr = np.sum([10, 20, 30, 40, 50]) # sum of all elements in the array
print(arr) # 150

150


In [6]:
import numpy as np

arr_1 = np.array([10, 20, 30, 40, 50])

print(np.mean(arr_1)) # average of the array elements
print(np.square(arr_1)) # square of each element in the array
print(np.sqrt(arr_1)) # square root of each element in the array 
print(np.max(arr_1)) # maximum element in the array
print(np.min(arr_1)) # minimum element in the array

30.0
[ 100  400  900 1600 2500]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
50
10


In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [10, 20, 30]])

print(arr)
print("Shape of array:", arr.shape) # (2, 3) # number of rows and columns
print("Number of dimensions:", arr.ndim) # 2 # number of dimensions
print("Size of array:", arr.size) # 6  # total number of elements
print("Data type of array elements:", arr.dtype) # int32 # 

[[ 1  2  3]
 [10 20 30]]
Shape of array: (2, 3)
Number of dimensions: 2
Size of array: 6
Data type of array elements: int64


In [8]:
import numpy as np

arr = np.array([ [[9, 8, 5] , [10, 20, 21]] , [[11, 22, 33] , [12, 24, 36]] , [[2,5,3],[5,8,4]] ])

print(arr)
print("Shape of array:", arr.shape) # (2, 3) # number of rows and columns
print("Number of dimensions:", arr.ndim) # 2 # number of dimensions
print("Size of array:", arr.size) # 6  # total number of elements


[[[ 9  8  5]
  [10 20 21]]

 [[11 22 33]
  [12 24 36]]

 [[ 2  5  3]
  [ 5  8  4]]]
Shape of array: (3, 2, 3)
Number of dimensions: 3
Size of array: 18


In [9]:
import numpy as np

arr = np.array(
    [
        
     [[1,2], [5,7], [9,8]],
     [[3,4], [6,8],[10,12]], 
     [[11,13], [14,16], [18,20]]
     
     ] )

print(arr[2, 1, 0])  
print(arr[-1, -2, -1])

print(arr[1,0,0])
print(arr[-2,-3,-2])

14
16
3
3


In [10]:
import numpy as np

arr =np.array([10,20,30,12,13])
condition = arr > 15
print(condition)  # [False  True  True False False]

[False  True  True False False]


In [11]:
# Q1

import numpy as np

arr = np.array([
    [12, 5, 7, 20],
    [13, 15, 8, 2],
    [10, 25, 6, 18],
    [4, 11, 30, 9]
])

print(arr[(arr > 10) | (arr < 5) & (arr != 15)])

[12 20 13 15  2 25 18  4 11 30]


In [ ]:
# Array Initialization

arr = np.zeros((3,4)) # 3 rows and 4 columns
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
arr =np.full((2,3),7) # 2 rows and 3 columns, filled with 7
print(arr)

[[7 7 7]
 [7 7 7]]


In [20]:
# Empty Array Initialization

arr = np.empty((2,4)) # 2 rows and 4 columns
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
#Pandas Library

import pandas as pd

In [24]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
<class 'pandas.core.frame.DataFrame'>


In [27]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
# print(df)

print(df.loc[1])

Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object


In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
# print(df)
print(df.loc[2,"Age"]) #output: 22

22


In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
print(df)

print(df.iloc[3,0]) # it will print 'David' because iloc uses integer-location based indexing

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
David


In [33]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
print(df)


      calaries  duration
day1       420        50
day2       380        40
day3       390        45
day4       410        60


In [37]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# print(df)
print(df.loc['day2'])
print(df.loc[ :'day2'])

calaries    380
duration     40
Name: day2, dtype: int64
      calaries  duration
day1       420        50
day2       380        40


In [42]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# print(df)
print(df.loc['day1'])
print(df.loc[[ 'day1','day3']])

calaries    420
duration     50
Name: day1, dtype: int64
      calaries  duration
day1       420        50
day3       390        45


In [ ]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# print(df)
print(df["calaries"]) # it will print all the values in the 'calaries' column

day1    420
day2    380
day3    390
day4    410
Name: calaries, dtype: int64


In [ ]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# print(df)
print (df.size) # it will print 8 because there are total 8 elements (4 rows * 2 columns)

8


In [ ]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# print(df)
print(df.shape) # it will print (4,2) because there are 4 rows and 2 columns

(4, 2)


In [ ]:
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# print(df)
print(df.values) # it will print the values of the DataFrame as a  return as the 2D  numpy array

[[420  50]
 [380  40]
 [390  45]
 [410  60]]


In [ ]:
#calculate the number of the data set
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
print("Number of rows :",len(df)) # returns the number of rows in the DataFrame


Number of rows : 4
Number of rows : 4


In [ ]:
#calculate the number of the data set
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
print("Number of rows :",df.shape[0]) # returns the number of rows in the DataFrame

Number of rows : 4


In [ ]:
#calculate the number of the data set
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
# last row od the data set
print(df.iloc[-1]) # it will print the last row
print(df.tail(1)) # it will print the last row

calaries    410
duration     60
Name: day4, dtype: int64
      calaries  duration
day4       410        60


In [65]:
#calculate the number of the data set
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}

print(df.columns)
print(list(df.columns))

Index(['calaries', 'duration'], dtype='object')
['calaries', 'duration']


In [66]:
#calculate the number of the data set
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
df["Distance"] = [5, 4, 4.5, 6]  # Adding a new column 'Distance' to the DataFrame
print(df)

      calaries  duration  Distance
day1       420        50       5.0
day2       380        40       4.0
day3       390        45       4.5
day4       410        60       6.0


In [70]:
#calculate the number of the data set
data = {
    "calaries":[420, 380, 390, 410],
    "duration":[50, 40, 45, 60],
}
# adding a new row foe the data set
df = pd.DataFrame(data,index=['day1','day2','day3','day4'])
new_row = pd.DataFrame({'calaries': [430], 'duration': [55]}, index=['day5'])
df = pd.concat([df, new_row])
print(df)

      calaries  duration
day1       420        50
day2       380        40
day3       390        45
day4       410        60
day5       430        55


In [74]:
import pandas as pd

data = {
    "calaries": [420, 380, 390, 410],
    "duration": [50, 40, 45, 60],
}

df = pd.DataFrame(data, index=['day1', 'day2', 'day3', 'day4'])

# Simple way to add new row
# df.loc['day5'] = [430, 55]
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])
df.loc[len(df)] = [440, 50]  # Another way to add a new row using the length of the DataFrame
print(df)


      calaries  duration
day1       420        50
day2       380        40
day3       390        45
day4       410        60
4          440        50


In [ ]:
data = {
    "Age":[20,21,19,18],
    "salary":[40000,50000,45000,60000],
}

df = pd.DataFrame(data)
print(df.describe()) # it will give the statistical summary of the DataFrame
# std is a standard deviation it measure the amount of variation or dispersion of a set of values


             Age        salary
count   4.000000      4.000000
mean   19.500000  48750.000000
std     1.290994   8539.125638
min    18.000000  40000.000000
25%    18.750000  43750.000000
50%    19.500000  47500.000000
75%    20.250000  52500.000000
max    21.000000  60000.000000


In [ ]:
data = {
    "Age":[20,21,19,18],
    "salary":[40000,50000,45000,60000],
}

df = pd.DataFrame(data)
print(df.mean()) # it will give the mean of each column in the DataFrame


Age          19.5
salary    48750.0
dtype: float64


In [77]:
data = {
    "Age":[20,21,19,18],
    "salary":[40000,50000,45000,60000],
}

df = pd.DataFrame(data)
print(df.sum()) # it will give the statistical summary of the DataFrame


Age           78
salary    195000
dtype: int64


In [ ]:
import pandas as pd

data = {
    "Age":[20,40,39,38],
    "salary":[40000,50000,45000,60000],
}

df = pd.DataFrame(data)
# print the age grater than 35
print(df[df["Age"] > 35]) # it will print the rows where age is greater than 35


   Age  salary
1   40   50000
2   39   45000
3   38   60000


In [4]:
data = {
    "Age":[20,40,39,38],
    "salary":[40000,50000,45000,60000],
}

df = pd.DataFrame(data)
# print the age grater than 35 and sallry greater than 45000
print(df[(df["Age"] > 35) & (df["salary"] > 45000)])


   Age  salary
1   40   50000
3   38   60000


In [11]:
import pandas as pd
df = pd.DataFrame({
    'product':['laptop','mouse,','keyboard','monitor','headset'],
    'unitslod':[12,50,34,20,40],
    'price':[120000,1500,3500,25000,6000],
    'Discount':[0.10,0.05,0.08,0.12,0.07]
})
#calculate the final price after discount for each product and add it as a new column
df['final_price'] = df['price'] * (1 - df['Discount'])
print(df)

    product  unitslod   price  Discount  final_price
0    laptop        12  120000      0.10     108000.0
1    mouse,        50    1500      0.05       1425.0
2  keyboard        34    3500      0.08       3220.0
3   monitor        20   25000      0.12      22000.0
4   headset        40    6000      0.07       5580.0


In [ ]:
import pandas as pd

df = pd.DataFrame({
    'product':['laptop','mouse','keyboard','monitor','headset'],
    'unitslod':[12,50,34,20,40],
    'price':[120000,1500,3500,25000,6000],
    'Discount':[0.10,0.05,0.08,0.12,0.07]
})

# simple revenue calculation
df['revenue'] = df['unitslod'] * df['price'] * (1 - df['Discount'])

print(df)


    product  unitslod   price  Discount    revenue
0    laptop        12  120000      0.10  1296000.0
1     mouse        50    1500      0.05    71250.0
2  keyboard        34    3500      0.08   109480.0
3   monitor        20   25000      0.12   440000.0
4   headset        40    6000      0.07   223200.0


In [18]:
import pandas as pd
df = pd.DataFrame({
    'product':['laptop','mouse,','keyboard','monitor','headset'],
    'unitslod':[12,50,34,20,40],
    'price':[120000,1500,3500,25000,6000],
    'Discount':[0.10,0.05,0.08,0.12,0.07]
})
#for above part 01 and part 02 add both resalts as new columns
df['final_price'] = df['price'] * (1 - df['Discount'])
df['Total Revenue'] = df['unitslod'] * df['price'] * (1 - df['Discount'])
print(df)

    product  unitslod   price  Discount  final_price  Total Revenue
0    laptop        12  120000      0.10     108000.0      1296000.0
1    mouse,        50    1500      0.05       1425.0        71250.0
2  keyboard        34    3500      0.08       3220.0       109480.0
3   monitor        20   25000      0.12      22000.0       440000.0
4   headset        40    6000      0.07       5580.0       223200.0


In [31]:
import pandas as pd
df = pd.DataFrame({
    'product':['laptop','mouse,','keyboard','monitor','headset'],
    'unitslod':[12,50,34,20,40],
    'price':[120000,1500,3500,25000,6000],
    'Discount':[0.10,0.05,0.08,0.12,0.07]
})

#filter  and display only products where total revenue is greater than 500000

df['TotalRevenue'] = df['unitslod'] * df['price'] * (1 - df['Discount'])
print(df[df['TotalRevenue'] > 500000])



  product  unitslod   price  Discount  TotalRevenue
0  laptop        12  120000       0.1     1296000.0


In [29]:
import pandas as pd
df = pd.DataFrame({
    'product':['laptop','mouse,','keyboard','monitor','headset'],
    'unitslod':[12,50,34,20,40],
    'price':[120000,1500,3500,25000,6000],
    'Discount':[0.10,0.05,0.08,0.12,0.07]
})
#calculate the total revenue of all  products cobine
df['revenue'] = df['unitslod'] * df['price'] * (1 - df['Discount'])
total_revenue = df['revenue'].sum()
print("Total Revenue of all products combined:", total_revenue)

Total Revenue of all products combined: 2139930.0


In [48]:

df = pd.DataFrame({
    'product':['laptop','mouse','keyboard','monitor','headset'],
    'unitslod':[12,50,34,20,40],
    'price':[120000,1500,3500,25000,6000],
    'Discount':[0.10,0.05,0.08,0.12,0.07]
})
  
# df.drop(labels=['Discount'], axis=1, inplace=True )
# df = df.drop(3,axis=0)
# df=df.drop(columns=['Discount'])

new_df = df.drop("Discount",axis=1)
print(new_df)


    product  unitslod   price
0    laptop        12  120000
1     mouse        50    1500
2  keyboard        34    3500
3   monitor        20   25000
4   headset        40    6000


In [51]:
import pandas as pd
df = pd.read_csv("./File_Handling/person_data.csv")
print(df)

   Name  Age    Country      City
0  Alex   16  Sri Lanka   Colombo
1   Mia   17  Australia    Sydney
2  Ravi   15        USA  New York
3  Sara   16         UK    London
4  Liam   17     Canada   Toronto


In [61]:
import pandas as pd

df = pd.read_json("./File_Handling/my_json.json")
print(df)

             0
0      sandaru
1           22
2  Bandaragama
3    Sri Lanka
